_target_: vr_env.scene.play_table_scene.PlayTableScene
_recursive_: false
data_path: ${data_path}
global_scaling: 0.8
euler_obs: ${robot.euler_obs}
robot_base_position: [0.3, 0.15, 0.45]
robot_base_orientation: [0, 0, 1.5707963]
robot_initial_joint_positions: [-0.3457686708019129, -0.15454379621111053, -0.6607497652179231, -2.431721569843283, -0.12811896258574057, 2.3050911768605884, -0.128854091294185]
surfaces: []
objects:
  fixed_objects:
    table:
      file: table/hightable.urdf
      initial_pos: [0.3, 0.7, 0.02]
      initial_orn: [0, 0, 0]
    bin:
      file: ais_objects/bin_10_30_50/bin_10_30_50.urdf
      initial_pos: [0.7, 0.75, 0.6]
      initial_orn: [1.57, 0, 0]
  movable_objects:
    hammer_3:
      file: tabletop/hammer_3/hammer_3.urdf
      initial_pos: [0.18, 0.67, 0.614]
      initial_orn: [0, 0, 0.5]
    frying_pan_4:
      file: tabletop/frying_pan_4/frying_pan_4.urdf
      initial_pos: [0.4, 0.5, 0.61]
      initial_orn: [0, 0, 0]
    tennis_racket:
      file: tabletop/tennis_racket/tennis_racket.urdf
      initial_pos: [0.15, 0.45, 0.618]
      initial_orn: [0, 0, 0]
    paint_brush:
      file: tabletop/paint_brush/paint_brush.urdf
      initial_pos: [0.4, 0.8, 0.61]
      initial_orn: [0, 0, 0]
    screwdriver:
      file: tabletop/screwdriver/screwdriver.urdf
      initial_pos: [0.1, 0.9, 0.614]
      initial_orn: [0, 0, 0]
    spatula_3:
      file: tabletop/spatula_3/spatula_3.urdf
      initial_pos: [-0.1, 0.6, 0.601]
      initial_orn: [0, 0, 0]
    teapot_3:
      file: tabletop/teapot_3/teapot_3.urdf
      initial_pos: [-0.15, 0.85, 0.642]
      initial_orn: [0, 0, -1]
    # tape:
    #   file: tabletop/tape/tape.urdf
    #   initial_pos: [0.4, 0.5, 0.618]
    #   initial_orn: [0, 0, 0]
    # tool_box:
    #   file: tabletop/tool_box/tool_box.urdf
    #   initial_pos: [-0.15, 0.85, 0.642]
    #   initial_orn: [0, 0, 0]
    # magnifying_glass:
    #   file: tabletop/magnifying_glass/magnifying_glass.urdf
    #   initial_pos: [0.4, 0.8, 0.607]
    #   initial_orn: [0, 0, 0]
    # scissors:
    #   file: tabletop/scissors/scissors.urdf
    #   initial_pos: [0.2, 0.45, 0.61]
    #   initial_orn: [0, 0, 0]
